### PR TITLE
Typo: C ABI -> C API

### PR DESCRIPTION
**Pull request by kelvin-273**

### CODE REVIEW

**Comment by ehuss** [comment]
Thanks for the PR!  I think the original appears correct to me. The default for an extern block is the [C ABI](https://doc.rust-lang.org/nightly/reference/items/external-blocks.html#abi), and I think what the sentence is trying to say is that the functions are being defined with that ABI.

**Comment by PureWhiteWu** [comment]
对的，ABI 的意思是 Application Binary Interface，和 API 是完全不一样的。

**Comment by kelvin-273** [comment]
Ah my bad. This would be my first time learning about ABIs.
Could it help if the this was hyperlinked to the Rust Reference or would that open the flood gate to a whole lot of unnecessary cross referencing?

**Comment by PureWhiteWu** [comment]
> Ah my bad. This would be my first time learning about ABIs.
> Could it help if the this was hyperlinked to the Rust Reference or would that open the flood gate to a whole lot of unnecessary cross referencing?

I think this is unnecessary. If someone does not understand these terms, they should go to Google themselves. After all, this book is not for beginners.

**Comment by kelvin-273** [comment]
Fair enoungh

**Pull request closed without merging**
