### PR TITLE
Follow-up for rust-lang/rust#74850

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by JohnTitor** [comment]
@Amanieu bors isn't here, could you approve and merge it manually?

**Comment by Amanieu** [comment]
I don't have write access to this repo.

**Comment by Dylan-DPC** [comment]
@Mark-Simulacrum you can merge this now :) thanks

**Comment by lzutao** [comment]
We need more maintainers with write access to this repo.

**Pull request merged**
