### PR TITLE
Fix link for `[T]`

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by lzutao** [comment]
It is now display as `slice: T`.

**Comment by JohnTitor** [comment]
Oh, good point! This should render it correctly now.

**Review by lzutao — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks @lzutao for reviewing!
@rust-lang/lang-docs Could someone also review this and #240? Thanks!

**Review by ehuss — APPROVED** [review]
👍

**Pull request merged**
