### PR TITLE
Follow-up of rust-lang/rust#75152

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by JohnTitor** [comment]
r? @Mark-Simulacrum until https://github.com/rust-lang/lang-team/issues/47 is done.

Btw, could I just r+ a submodule only PR for the docs like https://github.com/rust-lang/rust/pull/75168, or should I ask a review to ehuss or you?

**Comment by ehuss** [comment]
If this can get merged soon, I'll just include it in the regular update (I'm a few days late, but a little longer shouldn't hurt).

**Comment by JohnTitor** [comment]
@ehuss Awesome! It should fix the toolstate of the nomicon <3

**Comment by ehuss** [comment]
Posted https://github.com/rust-lang/rust/pull/75720

**Pull request merged**
