### PR TITLE
Update vector code examples

### PR DESCRIPTION
**Pull request by lukas9393**
Hi, I tried to finish the chapter about Vec. Unfortunately this chapter contains old source code that is not buildable. I had difficulties to get the code to work. Finally I found the last chapter with the actual working code.

I took this and updated the code examples. With this code it should now be possible, step by step, to evolve to the final code.

### CODE REVIEW

**Comment by Gankra** [comment]
Can you provide some insight into why you're using the unstable GlobalAlloc, and not the stable global alloc functions?

**Comment by Gankra** [comment]
(this is hard to express properly because of the super overloaded terms -- these functions at the bottom: https://doc.rust-lang.org/alloc/alloc/index.html#functions)

**Comment by lukas9393** [comment]
I have completely used the template from vec-final to update the tutorial.  I think the reason why the vec-final example does not use the stable API is that the stable api will be deprecated in the future.

**Review by Gankra — APPROVED** [review]
oh! i see, someone updated just the final part but not the code around it. ok, awesome!

**Pull request merged**
